spring.application.name=QuizDG

# Pede para o Spring (Hibernate) criar e atualizar as tabelas do banco automaticamente baseado nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Opcional, mas muito legal: mostra os comandos SQL no terminal para você ver a mágica acontecendo
spring.jpa.show-sql=true